/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingCodeRouteImport } from './routes/booking.$code'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCodeRoute = BookingCodeRouteImport.update({
  id: '/booking/$code',
  path: '/booking/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/manage': typeof ManageRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/booking/$code': typeof BookingCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/manage'
    | '/doctor'
    | '/reception'
    | '/booking/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/manage'
    | '/doctor'
    | '/reception'
    | '/booking/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/manage'
    | '/_authenticated/doctor'
    | '/_authenticated/reception'
    | '/booking/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ManageRoute: typeof ManageRoute
  BookingCodeRoute: typeof BookingCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$code': {
      id: '/booking/$code'
      path: '/booking/$code'
      fullPath: '/booking/$code'
      preLoaderRoute: typeof BookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ManageRoute: ManageRoute,
  BookingCodeRoute: BookingCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
