/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as MediaCoverageRouteImport } from './routes/media-coverage'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutDoctorRouteImport } from './routes/about-doctor'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as BookingCodeRouteImport } from './routes/booking.$code'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCoverageRoute = MediaCoverageRouteImport.update({
  id: '/media-coverage',
  path: '/media-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDoctorRoute = AboutDoctorRouteImport.update({
  id: '/about-doctor',
  path: '/about-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const BookingCodeRoute = BookingCodeRouteImport.update({
  id: '/booking/$code',
  path: '/booking/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/booking/$code': typeof BookingCodeRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/booking/$code': typeof BookingCodeRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-doctor': typeof AboutDoctorRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/manage': typeof ManageRoute
  '/mcp': typeof McpRoute
  '/media-coverage': typeof MediaCoverageRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/booking/$code': typeof BookingCodeRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-doctor'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/manage'
    | '/mcp'
    | '/media-coverage'
    | '/reviews'
    | '/sitemap.xml'
    | '/specialties'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/doctor'
    | '/reception'
    | '/settings'
    | '/booking/$code'
    | '/specialties/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-doctor'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/manage'
    | '/mcp'
    | '/media-coverage'
    | '/reviews'
    | '/sitemap.xml'
    | '/specialties'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/doctor'
    | '/reception'
    | '/settings'
    | '/booking/$code'
    | '/specialties/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-doctor'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/manage'
    | '/mcp'
    | '/media-coverage'
    | '/reviews'
    | '/sitemap.xml'
    | '/specialties'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/doctor'
    | '/_authenticated/reception'
    | '/_authenticated/settings'
    | '/booking/$code'
    | '/specialties/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutDoctorRoute: typeof AboutDoctorRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ManageRoute: typeof ManageRoute
  McpRoute: typeof McpRoute
  MediaCoverageRoute: typeof MediaCoverageRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialtiesRoute: typeof SpecialtiesRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BookingCodeRoute: typeof BookingCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-coverage': {
      id: '/media-coverage'
      path: '/media-coverage'
      fullPath: '/media-coverage'
      preLoaderRoute: typeof MediaCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-doctor': {
      id: '/about-doctor'
      path: '/about-doctor'
      fullPath: '/about-doctor'
      preLoaderRoute: typeof AboutDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/booking/$code': {
      id: '/booking/$code'
      path: '/booking/$code'
      fullPath: '/booking/$code'
      preLoaderRoute: typeof BookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SpecialtiesRouteChildren {
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
}

const SpecialtiesRouteChildren: SpecialtiesRouteChildren = {
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
}

const SpecialtiesRouteWithChildren = SpecialtiesRoute._addFileChildren(
  SpecialtiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutDoctorRoute: AboutDoctorRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ManageRoute: ManageRoute,
  McpRoute: McpRoute,
  MediaCoverageRoute: MediaCoverageRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialtiesRoute: SpecialtiesRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BookingCodeRoute: BookingCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
